window.rwSeasons = [
	{
		seasonNumber: '01',
		defaultTheme: 's01',
		defaultImage: 's01',
		defaultQuote: 'Fantastic!',
		episodes: [
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				escritor: 'Russel T. Davies',
				nome: 'Rose',
				quote: 'Did I mention? It also travels in time',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				nome: 'The End Of The World',
				escritor: 'Russel T. Davies',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				escritor: 'Mark Gatiss',
				nome: 'The Unquiet Dead',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'Aliens of London',
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Two Parter',
					next: ['01_05'],
				},
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'World War Three',
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Two Parter',
					prev: ['01_04'],
				},
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				escritor: 'Robert Shearman',
				nome: 'Dalek',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				escritor: 'Russel T. Davies',
				nome: 'The Long Game',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				escritor: 'Paul Cornell',
				nome: "Father's Day",
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'The Empty Child',
				escritor: 'Steven Moffat',

				arc: {
					type: 'Two Parter',
					next: ['01_10'],
				},
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				quote: 'Everybody lives, Rose.<br>Just this once....Everybody lives!',
				nome: "The Doctor Dance's",
				escritor: 'Steven Moffat',

				arc: {
					type: 'Two Parter',
					prev: ['01_09'],
				},
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				escritor: 'Russel T. Davies',
				nome: 'Boom Town',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				escritor: 'Russel T. Davies',
				nome: 'Bad Wolf',

				arc: {
					type: 'Three Parter',
					next: ['01_13'],
				},
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: 'The Parting Of The Ways',
				escritor: 'Russel T. Davies',

				arc: {
					type: 'Three Parter',
					prev: ['01_12'],
				},
			},
		],
	},
	{
		seasonNumber: '02',
		defaultTheme: 's02',
		defaultImage: 's02',
		defaultQuote: 'Rose Tyler, I...',
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Russel T. Davies',
				nome: 'The Christmas Invasion',
				special: true,
			},
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				nome: 'New Earth',
				escritor: 'Russel T. Davies',
				quote: 'New New Doctor!',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'Russell T. Davies',
				nome: 'Tooth and Claw',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'School Reunion',
				escritor: 'Toby Whithouse',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'The Girl in the Fireplace',
				escritor: 'Steven Moffat',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				escritor: 'Tom MacRae',
				nome: 'Rise of the Cybermen',

				arc: {
					type: 'Two Parter',
					next: ['02_06'],
				},
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				escritor: 'Tom MacRae',
				nome: 'The Age of Steel',

				arc: {
					type: 'Two Parter',
					prev: ['02_05'],
				},
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				escritor: 'Mark Gatiss',
				nome: "The Idiot's Lantern",
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				nome: 'The Impossible Planet',
				escritor: 'Matt Jones',
				arc: {
					type: 'Two Parter',
					next: ['02_09'],
				},
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'The Satan Pit',
				escritor: 'Matt Jones',
				arc: {
					type: 'Two Parter',
					prev: ['02_08'],
				},
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				escritor: 'Russel T. Davies',
				nome: 'Love & Monsters',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				escritor: 'Matthew Graham',
				nome: 'Fear Her',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'Army of Ghosts',
				escritor: 'Russel T. Davies',

				quote: 'Rose Tyler, I...',
				arc: {
					type: 'Two Parter',
					next: ['02_13'],
				},
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: 'Doomsday',
				image: 's02e13',
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Two Parter',
					prev: ['02_12'],
				},
			},
		],
	},
	{
		seasonNumber: '03',
		defaultTheme: 's03',
		defaultImage: 's03',
		defaultQuote: 'Allons-y!',
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Russel T. Davies',
				nome: 'The Runaway Bride',
				special: true,
			},
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				nome: 'Smith & Jones',
				escritor: 'Russel T. Davies',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'Gareth Roberts',
				nome: 'The Shakespear COde',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'Gridlock',
				escritor: 'Russell T. Davies',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'Daleks in Manhattan',
				escritor: 'Helen Raynor',
				arc: {
					type: 'Two Parter',
					next: ['03_05'],
				},
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				escritor: 'Helen Raynor',
				nome: 'Evolution of the Daleks',
				arc: {
					type: 'Two Parter',
					prev: ['03_04'],
				},
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				nome: 'The Lazarus Experiment',
				escritor: 'Chris Chibnall',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				escritor: 'Mark Gatiss',
				nome: '42',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				nome: 'Human Nature',
				escritor: 'Paul Cornell',
				arc: {
					type: 'Two Parter',
					next: ['03_09'],
				},
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'The Family of Blood',
				escritor: 'Paul Cornell',
				arc: {
					type: 'Two Parter',
					prev: ['03_08'],
				},
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				escritor: 'Steven Moffat',
				nome: 'Blink',
				quote: "Blink and you're dead",
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				escritor: 'Russel T. Davies',
				nome: 'Utopia',
				arc: {
					type: 'Three Parter',
					next: ['03_12', '03_13'],
				},
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'The Sound of the Drums',
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Three Parter',
					prev: ['03_11'],
					next: ['03_13'],
				},
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: 'The Last of the Timelords',
				theme: 's03e13',
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Three Parter',
					prev: ['03_11', '03_12'],
				},
			},
		],
	},
	{
		seasonNumber: '04',
		defaultTheme: 's04',
		defaultImage: 's04',
		defaultQuote: 'Allons-y!',
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Russel T. Davies',
				nome: 'Voyage of the Damned',
				image: 's04xmas01',
				special: true,
			},
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				nome: 'Partners in Crime',
				escritor: 'Russel T. Davies',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'James Moran',
				nome: 'The Fires of Pompeii',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'Planet of the Ood',
				escritor: 'Keith Temple',
				theme: 's04e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'The Sontaran Stratagem',
				escritor: 'Helen Raynor',
				arc: {
					type: 'Two Parter',
					next: ['04_05'],
				},
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				escritor: 'Helen Raynor',
				nome: 'The Poison Sky',
				arc: {
					type: 'Two Parter',
					prev: ['04_04'],
				},
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				escritor: 'Stephen Greenhorn',
				nome: "The Doctor's Daughter",
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				escritor: 'Gareth Roberts',
				nome: 'The Unicorn and the Wasp',
				quote: 'A murder, a mistery and Agatha Christie',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				nome: 'Silence in the Library',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					next: ['04_09'],
				},
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'Forest of the Dead',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['04_08'],
				},
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				escritor: 'Russel T. Davies',
				nome: 'Midnight',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				escritor: 'Russel T. Davies',
				nome: 'Turn Left',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'The Stolen Earth',
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Three Parter',
					next: ['04_13'],
				},
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: "The Journey's End",
				escritor: 'Russel T. Davies',
				arc: {
					type: 'Three Parter',
					prev: ['04_12'],
				},
			},
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				nome: 'The Next Doctor',
				image: 's04special1',
				escritor: 'Russel T. Davies',
				special: true,
			},
			{
				numeroEpisodioHuman: 'Easter Special',
				numeroEpisodio: 'easter',
				nome: 'The Planet of The Dead',
				image: 's04special2',
				escritor: 'Russell T Davies & Gareth Roberts',
				special: true,
			},
			{
				numeroEpisodioHuman: 'Special',
				numeroEpisodio: 'special1',
				nome: 'The Waters of Mars',
				image: 's04special3',
				escritor: 'Russell T Davies & Phil Ford',
				special: true,
			},
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'special2',
				nome: 'The End of Time - Part 1',
				image: 's04special4',
				theme: 's04special4',
				escritor: 'Russell T Davies',
				arc: {
					type: 'Two Parter',
					next: ['04_special2'],
				},
				special: true,
			},
			{
				numeroEpisodioHuman: 'Special',
				numeroEpisodio: 'special2',
				nome: 'The End of Time - Part 2',
				theme: 's04special4',
				imge: 's04special5 ',
				escritor: 'Russell T Davies',
				special: true,
				arc: {
					type: 'Two Parter',
					prev: ['04_special1'],
				},
				quote: "I don't want to go",
			},
		],
	},
	{
		seasonNumber: '05',
		defaultTheme: 's05',
		defaultImage: 's05',
		defaultQuote: 'Allons-y!',
		episodes: [
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				nome: 'The Eleventh Hour',
				escritor: 'Steven Moffat',
				image: 's05e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'Steven Moffat',
				nome: 'The Beast Below',
				image: 's05e02',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'Victory of the Daleks',
				escritor: 'Mark Gatiss',
				image: 's05e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'The Time of Angels',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					next: ['05_05'],
				},
				image: 's05e04',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'Flesh and Stone',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['05_04'],
				},
				image: 's05e05',
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				escritor: 'Toby Whithouse',
				nome: 'The Vampires of Venice',
				image: 's05e06',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				escritor: 'Simon Nye',
				nome: "Amy's Choice",
				image: 's05e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				nome: 'The Hungry Earth',
				escritor: 'Chris Chibnall',
				arc: {
					type: 'Two Parter',
					next: ['03_09'],
				},
				image: 's05e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'Cold Blood',
				escritor: 'Chris Chibnall',
				arc: {
					type: 'Two Parter',
					prev: ['05_08'],
				},
				image: 's05e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				escritor: 'Richard Curtis',
				nome: 'Vincent and the Doctor',
				image: 's05e10',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				escritor: 'Gareth Roberts',
				nome: 'The Lodger',
				image: 's05e11',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'The Pandorica Opens',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					next: ['05_13'],
				},
				image: 's05e12',
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: 'The Big Bang',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['05_12'],
				},
				image: 's05e13',
			},
		],
	},
	{
		seasonNumber: '06',
		defaultTheme: 's06',
		defaultImage: 's06',
		defaultQuote: 'Allons-y!',
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Steven Moffat',
				nome: 'A Christmas Carol',
				special: true,
				image: 's05xmas01',
			},
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				nome: 'The Impossible Astronaut',
				escritor: 'Steven Moffat',
				image: 's06e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'Steven Moffat',
				nome: 'Day of the Moon',
				image: 's06e02',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'The Curse of the Black Spot',
				escritor: 'Stephen Thompson',
				image: 's06e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: "The Doctor's Wife",
				escritor: 'Neil Gaiman',
				image: 's06e04',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'The Rebel Flesh',
				escritor: 'Matthew Graham',
				image: 's06e05',
				arc: {
					type: 'Two Parter',
					prev: ['06_06'],
				},
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				escritor: 'Matthew Graham',
				nome: 'The Almost People',
				image: 's06e06',
				arc: {
					type: 'Two Parter',
					next: ['06_05'],
				},
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				escritor: 'Steven Moffat',
				nome: 'A Good Man Goes to War',
				image: 's06e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				nome: "Let's Kill Hitler",
				escritor: 'Steven Moffat',
				image: 's06e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'Night Terrors',
				escritor: 'Mark Gatiss',
				image: 's06e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				escritor: 'Tom MacRae',
				nome: 'The Girl Who Waited',
				image: 's06e10',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				escritor: 'Toby Whithouse',
				nome: 'The God Complex',
				image: 's06e11',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'Closing Time',
				escritor: 'Gareth Roberts',
				image: 's06e12',
				arc: {
					type: 'Two Parter',
					next: ['06_13'],
				},
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: 'The Wedding of River Song',
				escritor: 'Steven Moffat',
				image: 's06e13',
				arc: {
					type: 'Two Parter',
					prev: ['06_12'],
				},
			},
		],
	},
	{
		seasonNumber: '07',
		defaultTheme: 's07',
		defaultImage: 's07',
		defaultQuote: 'Allons-y!',
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Steven Moffat',
				nome: 'The Doctor, the Widow and the Wardrobe',
				image: 's07xmas01',
				special: true,
			},
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				nome: 'Asylum of the Daleks',
				escritor: 'Steven Moffat',
				image: 's07e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'Chris Chibnall',
				nome: 'Dinosaurs on a Spaceship',
				image: 's07e02',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'A Town Called Mercy',
				escritor: 'Toby Whithouse',
				image: 's07e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'The Power of Three',
				escritor: 'Chris Chibnall',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'The Angels Take Manhattan',
				escritor: 'Steven Moffat',
				theme: 's07e05',
				image: 's07e05',
			},
			{
				numeroEpisodioHuman: 'Christmas Episode',
				numeroEpisodio: 'Christmas Episode',
				escritor: 'Steven Moffat',
				nome: 'The Snowmen',
				image: 's07xmas03',
				special: true,
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				nome: 'The Bells of Saint John',
				escritor: 'Steven Moffat',
				image: 's07e06',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				nome: 'The Rings of Akhaten',
				escritor: 'Neil Cross',
				theme: 's07e07',
				image: 's07e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				escritor: 'Mark Gatiss',
				nome: 'Cold War',
				image: 's07e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				escritor: 'Neil Cross',
				nome: 'Hide',
				image: 's07e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				nome: 'Journey to the Centre of the TARDIS',
				escritor: 'Stephen Thompson',
				image: 's07e10',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				nome: 'The Crimson Horror',
				escritor: 'Mark Gatiss',
				image: 's07e11',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'Nightmare in Silver',
				escritor: 'Neil Gaiman',
				image: 's07e12',
			},
			{
				numeroEpisodioHuman: '13',
				numeroEpisodio: '13',
				nome: 'The Name Of The Doctor',
				escritor: 'Steven Moffat',
				image: 's07e13',
				theme: 's07e13',
			},
			{
				numeroEpisodioHuman: '50th Aniversary',
				numeroEpisodio: '50th Aniversary',
				nome: 'The Name Of The Doctor',
				escritor: 'Steven Moffat',
				theme: '50th',
				image: '50th',
				quote: 'No sir..all thirteen of them',
			},
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				nome: 'The Time Of The Doctor',
				escritor: 'Steven Moffat',
				theme: 's07xmas02',
				image: 's07xmas02',
				special: true,
			},
		],
	},
	{
		seasonNumber: '08',
		defaultTheme: 's08',
		defaultImage: 's08',
		defaultQuote: 'Am i a good man?',
		episodes: [
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				escritor: 'Steven Moffat',
				nome: 'Deep Breath',
				image: 's08e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				nome: 'Into the Dalek',
				escritor: 'Phil Ford & Steven Moffat',
				image: 's08e02',
				quote: 'Am i a good man Clara?',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'The Robot of Sherwood',
				escritor: 'Chris Chibnall',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'Listen',
				escritor: 'Steven Moffat',
				image: 's08e04',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'Time Heist',
				escritor: 'Steve Thompson & Steven Moffat',
				image: 's08e05',
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				nome: 'The Caretaker',
				escritor: 'Gareth Roberts & Steven Moffat',
				image: 's08e06',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				nome: 'Kill the Moon',
				escritor: 'Peter Harness',
				image: 's08e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				escritor: 'Jamie Mathieson',
				nome: 'Mummy in the Orient Express',
				image: 's08e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				escritor: 'Jamie Mathieson',
				nome: 'Flatline',
				quote: 'I am the man who stops the monsters',
				image: 's08e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				nome: 'In the Forest of the Night',
				escritor: 'Frank Cottrell Boyce',
				image: 's08e10',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				nome: 'Dark Water',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					next: ['08_12'],
				},
				image: 's08e11',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'Death in Heaven',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['08_11'],
				},
				image: 's08e12',
			},
		],
	},
	{
		seasonNumber: '09',
		defaultTheme: 's09',
		defaultImage: 's09',
		defaultQuote: "Nothing's sad until it's over.<br>Then everything is.",
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Steven Moffat',
				nome: 'Last Christmas',
				quote: 'Every Christmas is Last Christmas',
				image: 's09xmas01',
				special: true,
			},

			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				escritor: 'Steven Moffat',
				nome: "The Magician's Apprentice",
				arc: {
					type: 'Two Parter',
					next: ['09_02'],
				},
				image: 's09e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				nome: "The Witch's Familiar",
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['09_01'],
				},
				image: 's09e02',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'Under the Lake',
				escritor: 'Toby Whithouse',
				arc: {
					type: 'Two Parter',
					next: ['09_04'],
				},
				image: 's09e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'Before the Flood',
				escritor: 'Toby Whithouse',
				arc: {
					type: 'Two Parter',
					prev: ['09_03'],
				},
				image: 's09e05',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'The Girl Who Died',
				escritor: 'Jamie Mathieson & Steven Moffat',
				arc: {
					type: 'Two Parter',
					next: ['09_06'],
				},
				image: 's09e05',
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				nome: 'The Woman Who Lived',
				escritor: 'Catherine Tregenna',
				arc: {
					type: 'Two Parter',
					prev: ['09_05'],
				},
				image: 's09e06',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				nome: 'The Zygon Invasion',
				escritor: 'Peter Harness',
				arc: {
					type: 'Two Parter',
					next: ['09_08'],
				},
				image: 's09e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				escritor: 'Peter Harness',
				nome: 'The Zygon Invasion',
				arc: {
					type: 'Two Parter',
					prev: ['09_07'],
				},
				image: 's09e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'Sleep No More',
				escritor: 'Mark Gatiss',
				image: 's09e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				nome: 'Face the Raven',
				escritor: 'Sarah Dollard',
				quote: 'Let me be brave!',
				image: 's09e10',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				nome: 'Heaven Sent',
				escritor: 'Steven Moffat',
				quote: 'HOW MANY SECONDS TO ETERNITY',
				arc: {
					type: 'Two Parter',
					next: ['09_12'],
				},
				image: 's09e11',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'Hell Bent',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['09_11'],
				},
				image: 's09e12',
			},
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Steven Moffat',
				nome: 'The Husbands of River Song',
				quote: 'Say WHEEEE!',
				image: 's09xmas02',
			},
		],
	},
	{
		seasonNumber: '10',
		defaultTheme: 's10',
		defaultImage: 's10',
		defaultQuote: '',
		episodes: [
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Steven Moffat',
				nome: 'The Return of Doctor Mysterio',
				image: 's10xmas01',
				special: true,
			},

			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				escritor: 'Steven Moffat',
				nome: 'The Pilot',
				image: 's10e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				nome: 'Smile',
				escritor: 'Frank Cottrell-Boyce',
				image: 's10e02',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				nome: 'Thin Ice',
				escritor: 'Sarah Dollard',
				image: 's10e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				nome: 'Knock Knock',
				escritor: 'Mike Bartlett',
				image: 's10e04',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				nome: 'Oxygen',
				escritor: 'Jamie Mathieson',
				image: 's10e05',
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				nome: 'Extremis',
				escritor: 'Steven Moffat',
				quote: 'Only in darkness we are revealed',
				arc: {
					type: 'Three Parter',
					next: ['10_07', '10_08'],
				},
				image: 's10e06',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				nome: 'The Pyramid at the End of the World',
				escritor: 'Peter Harness & Steven Moffat',
				arc: {
					type: 'Three Parter',
					next: ['10_08'],
					prev: ['10_06'],
				},
				image: 's10e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				escritor: 'Toby Whithouse',
				nome: 'The Lie of the Land',
				arc: {
					type: 'Three Parter',
					prev: ['10_06', '10_07'],
				},
				image: 's10e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'Empress of Mars',
				escritor: 'Mark Gatiss',
				image: 's10e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				nome: 'The Eaters of Light',
				escritor: 'Rona Munro',
				image: 's10e10',
			},
			{
				numeroEpisodioHuman: '11',
				numeroEpisodio: '11',
				nome: 'World Enougth and Time',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					next: ['10_12'],
				},
				quote: 'I waited for you...I waited for you',
				image: 's10e11',
			},
			{
				numeroEpisodioHuman: '12',
				numeroEpisodio: '12',
				nome: 'The Doctor Falls',
				escritor: 'Steven Moffat',
				arc: {
					type: 'Two Parter',
					prev: ['10_11'],
				},
				image: 's10e12',
				theme: 's09e10',
				quote: "Where's there's tears, there's hope",
			},
			{
				numeroEpisodioHuman: 'Christmas Special',
				numeroEpisodio: 'xmas',
				escritor: 'Steven Moffat',
				nome: 'T.B.A',
				image: 's10xmas02',
				special: true,
				theme: 's09e10',
			},
		],
	},
	{
		seasonNumber: '11',
		defaultTheme: '13theme',
		defaultImage: 's11',
		defaultQuote: '',
		episodes: [
			{
				numeroEpisodioHuman: '01',
				numeroEpisodio: '01',
				escritor: 'Chris Chibnall',
				nome: 'The Woman Who Fell to Earth',
				special: false,
				defaultImage: 's11e01',
			},
			{
				numeroEpisodioHuman: '02',
				numeroEpisodio: '02',
				escritor: 'Chris Chibnall',
				nome: 'The Ghost Monument',
				special: false,
				defaultImage: 's11e02',
			},
			{
				numeroEpisodioHuman: '03',
				numeroEpisodio: '03',
				escritor: 'Malorie Blackman & Chris Chibnall',
				nome: 'Rosa',
				special: false,
				defaultImage: 's11e03',
			},
			{
				numeroEpisodioHuman: '04',
				numeroEpisodio: '04',
				escritor: 'Chris Chibnall',
				nome: 'Arachnids in the UK',
				special: false,
				defaultImage: 's11e04',
			},
			{
				numeroEpisodioHuman: '05',
				numeroEpisodio: '05',
				escritor: 'Chris Chibnall',
				nome: 'The Tsuranga Conundrum',
				special: false,
				defaultImage: 's11e05',
			},
			{
				numeroEpisodioHuman: '06',
				numeroEpisodio: '06',
				escritor: 'Vinay Patel',
				nome: 'Demons of Punjab',
				special: false,
				defaultImage: 's11e06',
			},
			{
				numeroEpisodioHuman: '07',
				numeroEpisodio: '07',
				nome: 'Kerblam!',
				escritor: 'Pete McTighe',
				special: false,
				defaultImage: 's11e07',
			},
			{
				numeroEpisodioHuman: '08',
				numeroEpisodio: '08',
				nome: 'The Witchfinders',
				escritor: 'Joy Wilkison',
				special: false,
				defaultImage: 's11e08',
			},
			{
				numeroEpisodioHuman: '09',
				numeroEpisodio: '09',
				nome: 'It Takes You Away',
				escritor: 'Ed Hime',
				special: false,
				defaultImage: 's11e09',
			},
			{
				numeroEpisodioHuman: '10',
				numeroEpisodio: '10',
				nome: 'The Battle of Ranskoor Av Kolos',
				escritor: 'Chris Chibnall',
				special: false,
				defaultImage: 's11e10',
			},
			{
				numeroEpisodioHuman: 'New Year',
				numeroEpisodio: 'newyear',
				nome: 'Resolution',
				escritor: 'Chris Chibnall',
				special: true,
				defaultImage: 's11xmas',
			},
		],
	},
];
